server:
  tomcat:
    uri-encoding: UTF-8
  port: 8085

spring:
  application:
    name: litchi-product-server
  cloud:
    consul:
      host: localhost
      port: 8500
      #consul配置
      discovery:
        healthCheckPath: /health
        instance-id: ${spring.application.name}:${server.port}
        healthCheckInterval: 15s
        serviceName: ${spring.application.name}
  datasource:
    name: springboot
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      filter: stat
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/litchi?useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&useTimezone=true&serverTimezone=GMT
      username: root
      password: cjladmin
      initial-size: 1
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 1000MB
  resources:
    static-locations: file:F:\xchatresources\,classpath:/static,classpath:/public,classpath:/resources

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: cn.litchi.model.model

redis:
  host: 127.0.0.1
  port: 6379
  pool:
    max-active: 100
    max-idle: 10
    max-wait: 100000
  timeout: 0


logging:
  level:
    root: INFO
  file: litchi-product-server.log

